### ISSUE TITLE
break is not used Bash version 4.4.23

### ISSUE THREAD

**Issue by doggodanubus** [ncarusso/Solitaire_bash#1]
Line 72 has break which causes lots of spew and bash says it's unused. I commented it out and it passed testing by comparison with several other Solitaire variants. 

Bash version 4.4.23

**Comment by ncarusso** [comment]
Hi, 
I have just removed break from Line 72 in solitaire_bash_all_in_one file and also in Line 41 in external_functions_for_solitaire_bash file.

Thanks for reporting.
